application: diribeo2010
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images
  
- url: /.views
  static_dir: .views


- url: /tasks/currentversion
  script: currentversion.py

- url: /tasks/updateversion
  script: updateversion.py
  login: admin

- url: /.*
  script: main.py