application: diribeo2010
version: 1
runtime: python
api_version: 1
  
handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /stylesheets
  static_dir: stylesheets
  
- url: /images
  static_dir: images
  
- url: /.views
  static_dir: .views

- url: /tasks/updatedownloads_v1
  script: downloads.py
  login: admin

- url: /.*
  script: main.py
